trigger: 
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python src/extract_data.py
    test -f data/raw_data.json
  displayName: 'Test extraction script'

- script: |
    python src/transform_data.py
    test -f data/transformed_data.csv
  displayName: 'Test transformation script'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'AzureSubscription'
    appType: 'functionApp'
    AppName: 'myFunctionApp'
    package: $(System.DefaultWorkingDirectory)
  displayName: 'Deploy Azure Functions'